"""
scripts/update_docs.py
======================

Regenerate the AI-readable documentation of the whole app:

    docs/APP_STRUCTURE.md      - file/folder tree (which files exist)
    docs/APP_CODE_SNAPSHOT.md  - every file's full contents as text

Run it after any meaningful change so the docs stay in sync with the code:

    python scripts/update_docs.py

The walk skips the parts of the repo that are not part of the running app:
`test/` (pre-infection recovery snapshot), `venv/`, `.git/`, `data/`
(runtime state), `__pycache__/`, bytecode/backup files, and the generated
artifacts themselves. Everything else - code, config, agent definitions, and
the other markdown docs - is represented verbatim.
"""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT_STRUCTURE = ROOT / "docs" / "APP_STRUCTURE.md"
OUT_SNAPSHOT = ROOT / "docs" / "APP_CODE_SNAPSHOT.md"

SKIP_DIRS = {
    ".git",
    "venv",
    ".venv",
    "data",
    "test",
    "__pycache__",
    "node_modules",
    ".pytest_cache",
    ".mypy_cache",
}
SKIP_FILE_SUFFIXES = (".pyc", ".pyo", ".bak", ".log", ".tmp")
# The generated docs and the generator itself are never part of the snapshot.
SKIP_FILES = {"update_docs.py", "APP_STRUCTURE.md", "APP_CODE_SNAPSHOT.md"}

# Rough language hints used in fenced blocks of the code snapshot.
LANG_HINTS = {
    ".py": "python",
    ".js": "javascript",
    ".html": "html",
    ".css": "css",
    ".json": "json",
    ".md": "markdown",
    ".txt": "text",
    ".gitignore": "ignore",
    ".toml": "toml",
    ".yaml": "yaml",
    ".yml": "yaml",
}


def collect_files() -> list[str]:
    """All skip-aware, sorted, posix-style relative paths."""
    files = []
    for path in sorted(ROOT.rglob("*")):
        rel = path.relative_to(ROOT)
        if any(part in SKIP_DIRS for part in rel.parts):
            continue
        if path.is_file():
            name = path.name
            if name in SKIP_FILES:
                continue
            if name.lower().endswith(SKIP_FILE_SUFFIXES):
                continue
            files.append(rel.as_posix())
    return sorted(files)


def build_tree(files: list[str]) -> dict:
    """Nested dict from relative paths; leaves are None, dirs are dicts."""
    root: dict = {}
    for rel in files:
        parts = Path(rel).parts
        node = root
        for part in parts[:-1]:
            node = node.setdefault(part, {})
        node[parts[-1]] = None
    return root


def render_tree(root: dict) -> list[str]:
    """Render the nested dict as a README-style box-drawing tree."""
    lines: list[str] = []

    def emit(node: dict, prefix: str) -> None:
        dirs = sorted((k, v) for k, v in node.items() if isinstance(v, dict))
        leaves = sorted(k for k, v in node.items() if isinstance(v, type(None)))
        entries = dirs + [(leaf, None) for leaf in leaves]
        for i, (name, child) in enumerate(entries):
            last = i == len(entries) - 1
            connector = "└── " if last else "├── "
            lines.append(prefix + connector + name + ("/" if child else ""))
            if child:
                emit(child, prefix + ("    " if last else "│   "))

    emit(root, "")
    return lines


def fence_for(content: str) -> str:
    """Fence long enough to never collide with the content's backticks."""
    longest = 0
    run = 0
    for ch in content:
        if ch == "`":
            run += 1
            longest = max(longest, run)
        else:
            run = 0
    return "`" * max(3, longest + 1)


def lang_for(name: str) -> str:
    return LANG_HINTS.get(Path(name).suffix, "")


def build_structure_md(files: list[str], total_bytes: int) -> str:
    tree = "\n".join(render_tree(build_tree(files)))
    kb = total_bytes / 1024
    return f"""# APP_STRUCTURE - file layout of the app

> AUTO-GENERATED by `scripts/update_docs.py` - do not edit by hand.

This lists every file of the app (folders + names) except `test/` and
non-source artifacts. Regenerate after any change:

    venv/bin/python scripts/update_docs.py

Excluded on purpose: `test/` (pre-infection recovery snapshot), `venv/`,
`.git/`, `data/` (runtime state), `__pycache__/`, bytecode/backup files
(`*.pyc`, `*.bak`), and the two generated docs themselves.

## Tree

```
{tree}
```

## Stats

- Files: {len(files)}
- Total size: {total_bytes:,} bytes ({kb:,.1f} KB)

## Where to go next

- `README.md` - quickstart, folder inventory, model selection.
- `docs/CHANGELOG.md` - every change, newest first.
- `docs/RESTRUCTURE_README.md` - history of the current package layout.
- `docs/documentation_CREATING_AGENTS.md` - how to author new agents.
- `docs/APP_CODE_SNAPSHOT.md` - every file's full contents as text.
"""


def build_snapshot_md(files: list[str], total_bytes: int) -> str:
    kb = total_bytes / 1024
    header = f"""# APP_CODE_SNAPSHOT - the whole app as text

> AUTO-GENERATED by `scripts/update_docs.py` - do not edit by hand.

Every source file of the app, verbatim and in full, so an AI (or a human)
can read the entire project as a single document - names of files AND their
contents. Regenerate after any change:

    venv/bin/python scripts/update_docs.py

Files: {len(files)}   Total: {total_bytes:,} bytes ({kb:,.1f} KB)

- `docs/APP_STRUCTURE.md` - just the names/layout, much shorter.
"""
    blocks = [header]
    for rel in files:
        content = (ROOT / rel).read_text(encoding="utf-8", errors="replace")
        fence = fence_for(content)
        lang = lang_for(rel)
        blocks.append(f"## {rel}")
        blocks.append(f"{fence}{lang}")
        blocks.append(content.rstrip("\n"))
        blocks.append(fence)
        blocks.append("")
    return "\n".join(blocks)


def main() -> int:
    files = collect_files()
    total = 0
    for rel in files:
        total += len((ROOT / rel).read_bytes())

    structure = build_structure_md(files, total)
    snapshot = build_snapshot_md(files, total)

    OUT_STRUCTURE.write_text(structure, encoding="utf-8")
    OUT_SNAPSHOT.write_text(snapshot, encoding="utf-8")

    print(f"Wrote {len(files):,} files to:")
    print(f"  {OUT_STRUCTURE.relative_to(ROOT)}  ({len(structure.splitlines()):,} lines)")
    print(f"  {OUT_SNAPSHOT.relative_to(ROOT)}  ({len(snapshot.splitlines()):,} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())